version: 2

project_name: variance

builds:
  - skip: true

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  use: github-native
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch

milestones:
  - repo:
      owner: axiomhq
      name: variance
    close: true
    fail_on_error: false

release:
  github:
    owner: axiomhq
    name: variance
  prerelease: auto
  name_template: "Variance v{{ .Version }}"
  footer: |
    **Full Changelog**: https://github.com/axiomhq/variance/compare/{{ .PreviousTag }}...{{ .Tag }}
