version: 2

project_name: variance

builds:
  - skip: true

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  use: github-native

milestones:
  - repo:
      owner: axiomhq
      name: variance
    close: true
    fail_on_error: false

release:
  github:
    owner: axiomhq
    name: variance
  prerelease: auto
  name_template: "Variance v{{ .Version }}"
