name: PR

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - "1.19"
          - "1.20"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
          check-latest: true
      - uses: golangci/golangci-lint-action@v3

  test:
    name: Test
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - "1.19"
          - "1.20"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
          check-latest: true
          cache: true
      - name: Test
        run: make test

  ci-pass:
    name: CI Pass
    needs:
      - lint
      - test
    runs-on: ubuntu-latest
    if: always()
    steps:
      - if: |
          needs.lint.result != 'success' ||
          needs.test.result != 'success'
        run: exit 1
